FROM mysql:latest

ARG MYSQL_ROOT_PASSWORD
ARG MYSQL_DATABASE
ARG MYSQL_USER
ARG MYSQL_PASSWORD

ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=agrix
ENV MYSQL_USER=agrix
ENV MYSQL_PASSWORD=agrix

EXPOSE 3306
