version: "3"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./backend/back_env.env
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    volumes:
      - ./backend:/app/backend
    depends_on:
      - db
  db:
    image: postgres:latest
    env_file:
      - ./db_env.env
    environment:
      POSTGRES_DB: agrix
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
